- name: Upgrade de todos os pacotes do s.o
  yum:
    name: '*'
    state: latest
- name: instalacao do git cliente
  yum:
    name: git
    state: latest
- name: Configurar hosts do lab ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.2.2 control-node
        - 192.168.2.3 app01
        - 192.168.2.4 db01